# Generated by Django 4.1.5 on 2023-01-27 11:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Prediction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mois', models.IntegerField()),
                ('nb_employes', models.IntegerField()),
                ('emploi_crees', models.IntegerField()),
                ('franchise', models.IntegerField()),
                ('montant', models.FloatField()),
                ('creation', models.CharField(choices=[(1, 'Oui'), (0, 'Non')], max_length=3)),
                ('emplacement', models.CharField(choices=[(1, 'Ville'), (2, 'Campagne'), (0, 'Indéfini')], max_length=10)),
                ('cred_renouvelable', models.CharField(choices=[(1, 'Oui'), (0, 'Non')], max_length=3)),
                ('petit_pret', models.CharField(choices=[(1, 'Oui'), (0, 'Non')], max_length=3)),
                ('secteur', models.CharField(choices=[(0, 'Indéfini'), (11, 'Agriculture, sylviculture, pêche et chasse'), (21, 'Extraction minière, exploitation de carrières et extraction de pétrole et de gaz'), (22, 'Services publics'), (23, 'Construction'), (31, 'Fabrication'), (32, 'Fabrication'), (33, 'Fabrication'), (42, 'Commerce de gros'), (44, 'Commerce de détail'), (45, 'Commerce de détail'), (48, 'Transport et entreposage'), (49, 'Transport et entreposage'), (51, 'Information'), (52, 'Finances et assurances'), (53, 'Immobilier et location à bail'), (54, 'Services professionnels, scientifiques et techniques'), (55, 'Gestion de sociétés et d’entreprises'), (56, 'Administration et soutien et gestion des déchets / services d’assainissement'), (61, 'Services éducatifs'), (62, 'Soins de santé et aide sociale'), (71, 'Arts, divertissement et loisirs'), (72, 'Hébergement et services alimentaires'), (81, 'Autres services (sauf administration publique)'), (92, 'Administration publique')], max_length=200)),
            ],
        ),
    ]
